# Quickshell integration for Hyprland
exec-once = systemctl --user start quickshell.service
exec-once = systemctl --user start swaync.service

# Keybinds
bind = $mod, N, exec, quickshell msg toggle notifpanel
bind = $mod, C, exec, quickshell msg toggle configpanel
